### ISSUE TITLE
Crash on nil input passed to APM

### ISSUE THREAD

**Issue by timimsms** [MindscapeHQ/heroku-buildpack-raygun-apm#6]
Background:
- Application is a Ruby on Rails API with a React frontend client.
- Running the Raygun APM for Ruby on Rails on Heroku (Heroku-18 stack).
- Encountered an issue while testing a new application release
- We were running Scout APM prior to the release, now we are running Scout APM and Raygun APM
- We're using the Box API and Boxr Gem

Once the Raygun APM is introduced, we start to see errors arising from the Raygun APM (https://rubygems.org/gems/raygun-apm/versions/1.0.77-x86-mingw32).

```
/app/vendor/ruby-2.6.3/lib/ruby/2.6.0/uri/rfc3986_parser.rb:119 convert_to_uri
/app/vendor/ruby-2.6.3/lib/ruby/2.6.0/uri/generic.rb:1100 merge
/app/vendor/ruby-2.6.3/lib/ruby/2.6.0/uri/rfc3986_parser.rb:89 inject
/app/vendor/ruby-2.6.3/lib/ruby/2.6.0/uri/rfc3986_parser.rb:89 join
/app/vendor/ruby-2.6.3/lib/ruby/2.6.0/uri/common.rb:271 join
/app/vendor/bundle/ruby/2.6.0/gems/raygun-apm-1.0.77-x86_64-linux/lib/raygun/apm/hooks/httpclient.rb:14 do_request
/app/vendor/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient.rb:856 request
/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.1/lib/scout_apm/instruments/http_client.rb:37 block in request_with_scout_instruments
/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.1/lib/scout_apm/tracer.rb:34 instrument
/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.1/lib/scout_apm/tracer.rb:44 instrument
/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.1/lib/scout_apm/instruments/http_client.rb:36 request_with_scout_instruments
/app/vendor/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient.rb:765 post
/app/vendor/bundle/ruby/2.6.0/gems/boxr-1.14.0/lib/boxr/client.rb:153 block in post
/app/vendor/bundle/ruby/2.6.0/gems/boxr-1.14.0/lib/boxr/client.rb:219 with_auto_token_refresh
/app/vendor/bundle/ruby/2.6.0/gems/boxr-1.14.0/lib/boxr/client.rb:145 post
/app/vendor/bundle/ruby/2.6.0/gems/boxr-1.14.0/lib/boxr/collaborations.rb:39 add_collaboration
...
```

The underlying issue is a nil trying to be converted to a URI - but the application is actually performing differently and crashing much more severely when the Raygun APM is installed. I also tested with only the Raygun APM (i.e., no Scout) and the same issue occurred.

I'm continuing to investigate on our end to ensure the application isn't encountering this logical problem, but was wondering if there's a way to have a safer fallback here.

**Comment by alexbuyn** [comment]
thank you for the report, we were unable to reproduce the problem so far, but will add guards there. there release will come in the new year

**Comment by timimsms** [comment]
Great, thank you @alexbuyn. Looking forward to the update.

**Comment by Deacon-McIntyre** [comment]
Hi @timimsms , we've just released that change as version 1.0.78 of the raygun-apm gem. Let us know if that solves the problem, and if you were able to discover any other details from your investigation.

**Comment by weilandia** [comment]
Also seeing this after moving the raygunapm -- Brought down some core features related to uploading to Google Cloud.

```
/app/vendor/ruby-2.7.2/lib/ruby/2.7.0/uri/rfc3986_parser.rb:119 convert_to_uri
/app/vendor/ruby-2.7.2/lib/ruby/2.7.0/uri/generic.rb:1101 merge
/app/vendor/ruby-2.7.2/lib/ruby/2.7.0/uri/rfc3986_parser.rb:89 inject
/app/vendor/ruby-2.7.2/lib/ruby/2.7.0/uri/rfc3986_parser.rb:89 join
/app/vendor/ruby-2.7.2/lib/ruby/2.7.0/uri/common.rb:271 join
/app/vendor/bundle/ruby/2.7.0/gems/raygun-apm-1.0.78-x86_64-linux/lib/raygun/apm/hooks/httpclient.rb:30 raygun_apm_url
/app/vendor/bundle/ruby/2.7.0/gems/raygun-apm-1.0.78-x86_64-linux/lib/raygun/apm/hooks/httpclient.rb:16 do_request
/app/vendor/bundle/ruby/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:1104 follow_redirect
/app/vendor/bundle/ruby/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:854 request
/app/vendor/bundle/ruby/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:743 get
/app/vendor/bundle/ruby/2.7.0/gems/google-cloud-storage-1.29.2/lib/google/cloud/storage/service.rb:754 execute_once_with_response
/app/vendor/bundle/ruby/2.7.0/gems/google-cloud-storage-1.29.2/lib/google/cloud/storage/service.rb:723 block (2 levels) in execute_with_response
/app/vendor/bundle/ruby/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:61 block in retriable
/app/vendor/bundle/ruby/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:56 times
/app/vendor/bundle/ruby/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:56 retriable
/app/vendor/bundle/ruby/2.7.0/gems/google-cloud-storage-1.29.2/lib/google/cloud/storage/service.rb:720 block in execute_with_response
/app/vendor/bundle/ruby/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:61 block in retriable
/app/vendor/bundle/ruby/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:56 times
/app/vendor/bundle/ruby/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:56 retriable
/app/vendor/bundle/ruby/2.7.0/gems/google-cloud-storage-1.29.2/lib/google/cloud/storage/service.rb:712 execute_with_response
/app/vendor/bundle/ruby/2.7.0/gems/google-cloud-storage-1.29.2/lib/google/cloud/storage/service.rb:696 execute_or_queue_command_with_response
/app/vendor/bundle/ruby/2.7.0/gems/google-cloud-storage-1.29.2/lib/google/cloud/storage/service.rb:683 get_object_with_response
```

**Comment by weilandia** [comment]
I found my specific issue, which is related to the `raygun_apm_url` method and the Google Cloud Storage API. I'm guessing others are running into the same issue.

It is this method in Raygun that's causing the problem.

```
        def raygun_apm_url(uri, query)
          query && uri ? URI.join(uri, query).to_s : uri.to_s
        end
```

When uploading files to Google Cloud, the Raygun apm ends up calling the above with something like:

```
URI.join("https://storage.googleapis.com/storage/v1/b/[bucket]/o/[key]?alt=media", {"alt"=>"media"})
```

Which blows up. 

I'm not actually sure what this method is trying to do.  At first glance it seemed like there was a url and some query params and you were trying to join them together, so I thought you could just call something similar to Rails' `to_param` on `query` if it was a hash. On closer inspection that is not what `URI.join` is really designed to do, so not sure what's trying to be accomplished/what `query` is expected to look like.

**Comment by Deacon-McIntyre** [comment]
Thank you for those details @weilandia, that helps greatly! We'll update here when we have more information 👍

**Comment by Deacon-McIntyre** [comment]
Hi @weilandia and @timimsms , we've released `raygun-apm` version **1.0.81** with a fix to support Hash query params, please let us know if that resolves the issue.

Thanks!

**Comment by timimsms** [comment]
@Deacon-McIntyre the latest release isn't showing up / isn't able to be pulled into Heroku: https://rubygems.org/gems/raygun-apm-rails/versions

```
remote: -----> Installing dependencies using bundler 2.2.11
remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
remote:        Unable to find a spec satisfying raygun-apm (~> 1.0.53) in the set. Perhaps the
remote:        lockfile is corrupted? Found raygun-apm (1.0.81-universal-darwin), raygun-apm
remote:        (1.0.81-universal-darwin) that did not match the current platform.
remote:        Bundler Output: Unable to find a spec satisfying raygun-apm (~> 1.0.53) in the set. Perhaps the
remote:        lockfile is corrupted? Found raygun-apm (1.0.81-universal-darwin), raygun-apm
remote:        (1.0.81-universal-darwin) that did not match the current platform.
```

**Comment by timimsms** [comment]
Note: The following unblocked my issues deploying to Heroku:

```
bundle install
bundle lock --add-platform x86_64-linux
```

**Comment by Deacon-McIntyre** [comment]
That's great @timimsms, thanks for letting us know! We'll still look into why the universal-darwin version was being selected but I'm glad there is a workaround now.
